### ISSUE TITLE
NullPointerException in PhpStorm 7.1

### ISSUE THREAD

**Issue by peterjmag** [idok/jscs-plugin#2]
I'm getting the following NPE in PhpStorm 7.1 when changing any JS file with the jscs plugin enabled:

    com.intellij.lang.javascript.linter.JSLinterUtil.createAnnotation(Lcom/intellij/lang/annotation/AnnotationHolder;Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/editor/markup/TextAttributes;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;: com.intellij.lang.javascript.linter.JSLinterUtil.createAnnotation(Lcom/intellij/lang/annotation/AnnotationHolder;Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/editor/markup/TextAttributes;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;
    java.lang.NoSuchMethodError: com.intellij.lang.javascript.linter.JSLinterUtil.createAnnotation(Lcom/intellij/lang/annotation/AnnotationHolder;Lcom/intellij/lang/annotation/HighlightSeverity;Lcom/intellij/openapi/editor/markup/TextAttributes;Lcom/intellij/openapi/util/TextRange;Ljava/lang/String;)Lcom/intellij/lang/annotation/Annotation;
        at com.jscs.JscsExternalAnnotator.createAnnotation(JscsExternalAnnotator.java:188)
        at com.jscs.JscsExternalAnnotator.apply(JscsExternalAnnotator.java:137)
        at com.jscs.JscsExternalAnnotator.apply(JscsExternalAnnotator.java:49)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:194)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:43)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$2$1.run(ExternalToolPass.java:142)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$2.run(ExternalToolPass.java:135)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$3.run(ExternalToolPass.java:170)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:297)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:420)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:695)
        at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:150)

In addition, I'm getting "Version n.a." in the plugin config:

![phpstorm - jscs plugin config issue](https://cloud.githubusercontent.com/assets/352105/4273690/1c4561e6-3ced-11e4-8889-a3cad68ee601.png)

Some details about my environment:

    $ jscs --version
    1.6.1
    $ which jscs
    /usr/local/bin/jscs
    $ node --version
    v0.10.26
    $ which node
    /usr/local/bin/node

- PhpStorm 7.1.3 (PS-133.982)
- OS X 10.9.4

Could this be related / similar to https://github.com/idok/scss-lint-plugin/issues/1?

**Comment by idok** [comment]
Is this still relevant?

**Comment by peterjmag** [comment]
I haven't seen the error since this plugin was added to WebStorm 9 / PhpStorm 8, so I'll go ahead and close this issue. Thanks!
