### ISSUE TITLE
AssertionError in IntelliJ 15: Already disposed: Project (Disposed) <PROJECT-NAME>

### ISSUE THREAD

**Issue by jcassee** [idok/jscs-plugin#24]
This is the stack trace:

```
Already disposed: Project (Disposed) <PROJECT-NAME>
java.lang.AssertionError: Already disposed: Project (Disposed) <PROJECT-NAME>
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:265)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:52)
    at com.intellij.openapi.components.ServiceKt.getStateStore(service.kt:29)
    at com.intellij.openapi.project.impl.ProjectImpl.getStateStore(ProjectImpl.java:202)
    at com.intellij.openapi.project.impl.ProjectImpl.getBasePath(ProjectImpl.java:251)
    at com.wix.utils.FileUtils.relativePath(FileUtils.java:50)
    at com.wix.ThreadLocalTempActualFile.createFile(ThreadLocalTempActualFile.java:109)
    at com.wix.ThreadLocalTempActualFile.getOrCreateFile(ThreadLocalTempActualFile.java:47)
    at com.wix.ActualFile2.getOrCreateActualFile(ActualFile2.java:53)
    at com.jscs.JscsExternalAnnotator.doAnnotate(JscsExternalAnnotator.java:241)
    at com.jscs.JscsExternalAnnotator.doAnnotate(JscsExternalAnnotator.java:47)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.f(ExternalToolPass.java:184)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:46)
    at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:126)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
    at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
    at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

If I can do anything else to help debug the problem please let me know.

**Comment by jcassee** [comment]
Ah, I see IntelliJ 15 already supports jscs without a plugin. I have disabled the plugin. Leaving the bug open, but feel free to close.

**Comment by Dzenly** [comment]
Actually, IntelliJ supports only code inspection without this plugin. But if this plugin is enabled there is 'Code' -> 'JSCS fix' menu, which allow to automatically fix some JSCS issues.
So, this AssertionError bothers me. :)
