### ISSUE TITLE
Fails to initialize on Webstorm 9

### ISSUE THREAD

**Issue by Nijikokun** [idok/jscs-plugin#3]
Error is as follows:

```
Plugin 'com.wix.jscs' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NoClassDefFoundError: com/intellij/lang/javascript/json/JSONLanguageDialect
    at com.jscs.config.JscsConfigFileType.<init>(JscsConfigFileType.java:16)
    at com.jscs.config.JscsConfigFileType.<clinit>(JscsConfigFileType.java:11)
    at com.jscs.config.JscsConfigFileTypeFactory.createFileTypes(JscsConfigFileTypeFactory.java:10)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:167)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initComponent(FileTypeManagerImpl.java:357)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:557)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:599)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
    at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
    at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:121)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:357)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:112)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:108)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:510)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:492)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:156)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:68)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.lang.javascript.json.JSONLanguageDialect PluginClassLoader[com.wix.jscs, 1.0.1]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 35 more
```

On OSX Mavericks, no additional plugins installed other than the editor defaults.

**Comment by idok** [comment]
Thanks for the feedback.
Fixed compatibility issue with WebStorm 9 and Intellij 14, as you noticed jscs in built in into these versions. The jscs plugin has minor features like presets and esnext support that differs it from the bundled plugin, if you do not need those, you can use the bundled plugin.
